---

- hosts: all
  sudo: True
  # accelerate: True
  user: $user

  tasks:
    - name: update apt
      action: command /usr/bin/apt-get update

    - name: install useful stuff
      action: apt pkg={{ item }} state=installed
      with_items:
        - git

