---

- hosts: all
  sudo: True
  # accelerate: True
  user: $user

  tasks:
    - name: install useful stuff
      action: apt pkg={{ item }} state=installed
      with_items:
        - git
        - ncdu

    - name: set locale to GB
      command: locale-gen en_GB.UTF-8
