---


- hosts: vagrant
  user: $user
  sudo: true


  tasks:
    - name: Install Mysql package
      apt: name={{ item }} state=installed
      with_items:
       - mysql-server
       - libapache2-mod-auth-mysql
       - php5-mysql

    # - name: set root mysql password
    #   command: /usr/bin/mysqladmin -u root password '{{ mysqlrootpassword }}' 

    # - name: mysql_secure_installation
    #   command: mysql_secure_installation
