---

- hosts: vagrant
  user: $user
  # accelerate: True
  sudo: True

  tasks:
    - name: grant permissions
      command: chmod 755 {{ documentroot }}

    - name: add apache2 site
      action: template src=files/site.conf.template dest=/etc/apache2/sites-available/{{ servername }}.conf

    - name: create the apache2 site log folder
      command: mkdir -p /var/log/apache2/{{ servername }}/

    - name: enable site
      command: sudo a2ensite {{ servername }}.conf

    - name: restart apache2 again
      command: service apache2 restart
