---

- hosts: vagrant
  user: $user
  # accelerate: True
  sudo: True

  tasks:
    # - name: write nginx.conf
    #   action: template src=files/nginx.conf dest=/etc/nginx/nginx.conf
    #   tags:
    #     - finally

    - name: grant permissions
      command: chmod 755 {{ documentroot }}

    - name: add apache2 site
      action: template src=files/site.conf.template dest=/etc/apache2/sites-available/{{ servername }}.conf

    - name: chmod the apache2 log files
      command: mkdir -p /var/log/apache2/{{ servername }}/

    - name: enable site
      command: sudo a2ensite {{ servername }}.conf

    - name: restart apache2 again
      command: service apache2 restart
